enum Difficulty { easy, medium, hard }

enum Speaker { system, user }

class ConversationTurn {
  final Speaker speaker;
  final String text;

  const ConversationTurn({required this.speaker, required this.text});
}

class ConversationScenario {
  final String id;
  final String title;
  final Difficulty difficulty;
  final List<ConversationTurn> turns;

  const ConversationScenario({
    required this.id,
    required this.title,
    required this.difficulty,
    required this.turns,
  });

  int get userTurnsCount => turns.where((t) => t.speaker == Speaker.user).length;
}

const conversationScenarios = <ConversationScenario>[
  ConversationScenario(
    id: 'easy_help',
    title: 'Asking for Help',
    difficulty: Difficulty.easy,
    turns: [
      ConversationTurn(speaker: Speaker.system, text: 'Hi! Can I help you?'),
      ConversationTurn(speaker: Speaker.user, text: 'Excuse me.'),
      ConversationTurn(speaker: Speaker.system, text: 'Sure. What do you need?'),
      ConversationTurn(speaker: Speaker.user, text: 'Can you help me?'),
      ConversationTurn(speaker: Speaker.system, text: 'Okay. What is the problem?'),
      ConversationTurn(speaker: Speaker.user, text: 'I do not understand.'),
      ConversationTurn(speaker: Speaker.system, text: 'No problem. I will explain.'),
      ConversationTurn(speaker: Speaker.user, text: 'Thank you.'),
      ConversationTurn(speaker: Speaker.system, text: 'Where are you going?'),
      ConversationTurn(speaker: Speaker.user, text: 'Where is the restroom?'),
      ConversationTurn(speaker: Speaker.system, text: 'It is over there.'),
      ConversationTurn(speaker: Speaker.user, text: 'Okay, thank you.'),
      ConversationTurn(speaker: Speaker.system, text: 'Do you need anything else?'),
      ConversationTurn(speaker: Speaker.user, text: 'No, thank you.'),
      ConversationTurn(speaker: Speaker.system, text: 'Alright. Have a nice day!'),
      ConversationTurn(speaker: Speaker.user, text: 'You too.'),
      ConversationTurn(speaker: Speaker.system, text: 'Bye!'),
      ConversationTurn(speaker: Speaker.user, text: 'Goodbye.'),
      ConversationTurn(speaker: Speaker.system, text: 'See you next time!'),
      ConversationTurn(speaker: Speaker.user, text: 'See you.'),
    ],
  ),
  ConversationScenario(
    id: 'med_food',
    title: 'Ordering Food',
    difficulty: Difficulty.medium,
    turns: [
      ConversationTurn(speaker: Speaker.system, text: 'Welcome! What would you like?'),
      ConversationTurn(speaker: Speaker.user, text: 'I would like to order a chicken meal, please.'),
      ConversationTurn(speaker: Speaker.system, text: 'Would you like a drink?'),
      ConversationTurn(speaker: Speaker.user, text: 'Yes, please. A water.'),
      ConversationTurn(speaker: Speaker.system, text: 'For here or to go?'),
      ConversationTurn(speaker: Speaker.user, text: 'To go, please.'),
      ConversationTurn(speaker: Speaker.system, text: 'Anything else?'),
      ConversationTurn(speaker: Speaker.user, text: 'No, thank you.'),
      ConversationTurn(speaker: Speaker.system, text: 'That will be two hundred fifty pesos.'),
      ConversationTurn(speaker: Speaker.user, text: 'Do you accept credit cards or cash only?'),
      ConversationTurn(speaker: Speaker.system, text: 'We accept both.'),
      ConversationTurn(speaker: Speaker.user, text: 'Okay, I will pay by card.'),
      ConversationTurn(speaker: Speaker.system, text: 'Please tap your card.'),
      ConversationTurn(speaker: Speaker.user, text: 'Here you go.'),
      ConversationTurn(speaker: Speaker.system, text: 'Your order will be ready soon.'),
      ConversationTurn(speaker: Speaker.user, text: 'Thank you.'),
      ConversationTurn(speaker: Speaker.system, text: 'Here is your order.'),
      ConversationTurn(speaker: Speaker.user, text: 'Great. Have a nice day.'),
      ConversationTurn(speaker: Speaker.system, text: 'You too!'),
      ConversationTurn(speaker: Speaker.user, text: 'Goodbye.'),
    ],
  ),
  ConversationScenario(
    id: 'hard_support',
    title: 'Customer Support',
    difficulty: Difficulty.hard,
    turns: [
      ConversationTurn(speaker: Speaker.system, text: 'Hello, how can I help today?'),
      ConversationTurn(speaker: Speaker.user, text: 'I would like to report an issue with my billing statement.'),
      ConversationTurn(speaker: Speaker.system, text: 'What seems to be the problem?'),
      ConversationTurn(speaker: Speaker.user, text: 'Before we proceed, I want to confirm the total cost including fees.'),
      ConversationTurn(speaker: Speaker.system, text: 'Sure. Can you share more details?'),
      ConversationTurn(speaker: Speaker.user, text: 'I was charged twice for the same transaction.'),
      ConversationTurn(speaker: Speaker.system, text: 'When did it happen?'),
      ConversationTurn(speaker: Speaker.user, text: 'It happened yesterday around three p m.'),
      ConversationTurn(speaker: Speaker.system, text: 'Do you have a receipt or proof of payment?'),
      ConversationTurn(speaker: Speaker.user, text: 'Yes, I can provide a screenshot.'),
      ConversationTurn(speaker: Speaker.system, text: 'We will investigate and get back to you.'),
      ConversationTurn(speaker: Speaker.user, text: 'Could you explain the process step by step so I can follow?'),
      ConversationTurn(speaker: Speaker.system, text: 'First we verify the charge, then we issue a refund if needed.'),
      ConversationTurn(speaker: Speaker.user, text: 'How long will the refund usually take?'),
      ConversationTurn(speaker: Speaker.system, text: 'Three to five business days.'),
      ConversationTurn(speaker: Speaker.user, text: 'Okay, I understand.'),
      ConversationTurn(speaker: Speaker.system, text: 'Is there anything else I can help with?'),
      ConversationTurn(speaker: Speaker.user, text: 'I appreciate your help. Thank you.'),
      ConversationTurn(speaker: Speaker.system, text: 'You are welcome. Have a good day.'),
      ConversationTurn(speaker: Speaker.user, text: 'You too. Goodbye.'),
    ],
  ),
  ConversationScenario(
    id: 'easy_greeting',
    title: 'Simple Greeting',
    difficulty: Difficulty.easy,
    turns: [
      ConversationTurn(speaker: Speaker.system, text: 'Hello! How are you?'),
      ConversationTurn(speaker: Speaker.user, text: 'Hi, I am fine.'),
      ConversationTurn(speaker: Speaker.system, text: 'That is good. What is your name?'),
      ConversationTurn(speaker: Speaker.user, text: 'My name is John.'),
      ConversationTurn(speaker: Speaker.system, text: 'Nice to meet you, John.'),
      ConversationTurn(speaker: Speaker.user, text: 'Nice to meet you too.'),
      ConversationTurn(speaker: Speaker.system, text: 'How is the weather today?'),
      ConversationTurn(speaker: Speaker.user, text: 'It is sunny and warm.'),
      ConversationTurn(speaker: Speaker.system, text: 'That sounds pleasant.'),
      ConversationTurn(speaker: Speaker.user, text: 'Yes, it is very nice.'),
    ],
  ),
  ConversationScenario(
    id: 'easy_directions',
    title: 'Asking for Directions',
    difficulty: Difficulty.easy,
    turns: [
      ConversationTurn(speaker: Speaker.system, text: 'Can I help you find something?'),
      ConversationTurn(speaker: Speaker.user, text: 'Yes, where is the library?'),
      ConversationTurn(speaker: Speaker.system, text: 'It is down the street.'),
      ConversationTurn(speaker: Speaker.user, text: 'How far is it?'),
      ConversationTurn(speaker: Speaker.system, text: 'About ten minutes walk.'),
      ConversationTurn(speaker: Speaker.user, text: 'Is it near the park?'),
      ConversationTurn(speaker: Speaker.system, text: 'Yes, right next to it.'),
      ConversationTurn(speaker: Speaker.user, text: 'Thank you very much.'),
      ConversationTurn(speaker: Speaker.system, text: 'You are welcome. Enjoy!'),
      ConversationTurn(speaker: Speaker.user, text: 'Goodbye.'),
    ],
  ),
  ConversationScenario(
    id: 'med_hotel',
    title: 'Hotel Reservation',
    difficulty: Difficulty.medium,
    turns: [
      ConversationTurn(speaker: Speaker.system, text: 'Welcome to City Hotel. How can I assist you?'),
      ConversationTurn(speaker: Speaker.user, text: 'I would like to make a reservation for next week.'),
      ConversationTurn(speaker: Speaker.system, text: 'Of course. How many nights will you stay?'),
      ConversationTurn(speaker: Speaker.user, text: 'Three nights. What is the price per night?'),
      ConversationTurn(speaker: Speaker.system, text: 'It depends on the room type. Would you prefer a single or double room?'),
      ConversationTurn(speaker: Speaker.user, text: 'I need a double room with a view.'),
      ConversationTurn(speaker: Speaker.system, text: 'That will be three hundred dollars per night.'),
      ConversationTurn(speaker: Speaker.user, text: 'Does the price include breakfast?'),
      ConversationTurn(speaker: Speaker.system, text: 'No, breakfast is thirty dollars extra per day.'),
      ConversationTurn(speaker: Speaker.user, text: 'Okay, I will take it with breakfast included.'),
      ConversationTurn(speaker: Speaker.system, text: 'Great! What dates will you be staying?'),
      ConversationTurn(speaker: Speaker.user, text: 'From Monday to Thursday next week.'),
      ConversationTurn(speaker: Speaker.system, text: 'And what is your name?'),
      ConversationTurn(speaker: Speaker.user, text: 'My name is Sarah Miller.'),
      ConversationTurn(speaker: Speaker.system, text: 'Perfect. I will send a confirmation email shortly.'),
      ConversationTurn(speaker: Speaker.user, text: 'Thank you. What time is check in?'),
      ConversationTurn(speaker: Speaker.system, text: 'Check in is at three p m and check out at eleven a m.'),
      ConversationTurn(speaker: Speaker.user, text: 'That works fine for me.'),
    ],
  ),
  ConversationScenario(
    id: 'med_shopping',
    title: 'Shopping Conversation',
    difficulty: Difficulty.medium,
    turns: [
      ConversationTurn(speaker: Speaker.system, text: 'Good afternoon. Looking for anything specific?'),
      ConversationTurn(speaker: Speaker.user, text: 'Yes, I am looking for a blue shirt in size medium.'),
      ConversationTurn(speaker: Speaker.system, text: 'We have several options over there. Would you like to try them on?'),
      ConversationTurn(speaker: Speaker.user, text: 'Sure. Can I use the fitting room?'),
      ConversationTurn(speaker: Speaker.system, text: 'Of course. You can take up to five items at a time.'),
      ConversationTurn(speaker: Speaker.user, text: 'Okay, I will take these three shirts and a pair of jeans.'),
      ConversationTurn(speaker: Speaker.system, text: 'Great. The fitting room is over there. Let me know if you need any other sizes.'),
      ConversationTurn(speaker: Speaker.user, text: 'Actually, these fit well. How much are they?'),
      ConversationTurn(speaker: Speaker.system, text: 'The shirts are forty five dollars each and the jeans are eighty dollars.'),
      ConversationTurn(speaker: Speaker.user, text: 'Do you have any discounts today?'),
      ConversationTurn(speaker: Speaker.system, text: 'We have a twenty percent off sale on everything.'),
      ConversationTurn(speaker: Speaker.user, text: 'Wonderful! I will take all of them.'),
      ConversationTurn(speaker: Speaker.system, text: 'Perfect. Would you like to pay with card or cash?'),
      ConversationTurn(speaker: Speaker.user, text: 'Card, please.'),
    ],
  ),
  ConversationScenario(
    id: 'hard_technical',
    title: 'Technical Support Call',
    difficulty: Difficulty.hard,
    turns: [
      ConversationTurn(speaker: Speaker.system, text: 'Thank you for calling technical support. What is the issue?'),
      ConversationTurn(speaker: Speaker.user, text: 'My computer is running very slowly. I think there might be a virus.'),
      ConversationTurn(speaker: Speaker.system, text: 'I understand your concern. First, let us check your system. Can you turn it off and on again?'),
      ConversationTurn(speaker: Speaker.user, text: 'I already tried that, but it did not help. What should I do next?'),
      ConversationTurn(speaker: Speaker.system, text: 'Let me guide you through it. Open your device manager and look for any unknown devices.'),
      ConversationTurn(speaker: Speaker.user, text: 'I see three unknown devices. Is that normal?'),
      ConversationTurn(speaker: Speaker.system, text: 'That could be the problem. Can you tell me what they say?'),
      ConversationTurn(speaker: Speaker.user, text: 'They just show question marks. I cannot see the names.'),
      ConversationTurn(speaker: Speaker.system, text: 'We need to update your drivers. Download the latest driver software from the manufacturer website.'),
      ConversationTurn(speaker: Speaker.user, text: 'How do I know which website is the official one?'),
      ConversationTurn(speaker: Speaker.system, text: 'Search for your computer model and go to the official support page.'),
      ConversationTurn(speaker: Speaker.user, text: 'Okay, I found it. Now what are the installation steps?'),
      ConversationTurn(speaker: Speaker.system, text: 'Just run the installer and follow the prompts. It should take about ten minutes.'),
      ConversationTurn(speaker: Speaker.user, text: 'Got it. I will do that now and call you back if there are any issues.'),
      ConversationTurn(speaker: Speaker.system, text: 'Sound good. We are available twenty four seven. Thank you for calling.'),
    ],
  ),
  ConversationScenario(
    id: 'hard_insurance',
    title: 'Insurance Claim',
    difficulty: Difficulty.hard,
    turns: [
      ConversationTurn(speaker: Speaker.system, text: 'Good morning. Thank you for contacting our insurance company. How may I help?'),
      ConversationTurn(speaker: Speaker.user, text: 'I need to file a claim for my car accident. It happened two days ago.'),
      ConversationTurn(speaker: Speaker.system, text: 'I am sorry to hear that. I will help you with this. What is your policy number?'),
      ConversationTurn(speaker: Speaker.user, text: 'It is zero one two three four five six seven eight.'),
      ConversationTurn(speaker: Speaker.system, text: 'Thank you. Can you describe what happened in detail?'),
      ConversationTurn(speaker: Speaker.user, text: 'Another car hit me from behind while I was stopped at a red light.'),
      ConversationTurn(speaker: Speaker.system, text: 'Were there any witnesses at the scene?'),
      ConversationTurn(speaker: Speaker.user, text: 'Yes, there were two witnesses and I have their contact information.'),
      ConversationTurn(speaker: Speaker.system, text: 'Excellent. Can you provide those details? Also, did you file a police report?'),
      ConversationTurn(speaker: Speaker.user, text: 'Yes, the police report number is B L M two three four five six seven. And here are the witness numbers.'),
      ConversationTurn(speaker: Speaker.system, text: 'Perfect. Do you have an estimate for the repairs?'),
      ConversationTurn(speaker: Speaker.user, text: 'I got one from a mechanic. The damage is estimated at five thousand dollars.'),
      ConversationTurn(speaker: Speaker.system, text: 'We will need to verify that with our inspector. How soon can we schedule that?'),
      ConversationTurn(speaker: Speaker.user, text: 'Anytime this week would work. I am flexible.'),
      ConversationTurn(speaker: Speaker.system, text: 'Great. Our inspector will contact you within twenty four hours to set an appointment. Is there anything else?'),
      ConversationTurn(speaker: Speaker.user, text: 'When can I expect the claim decision?'),
      ConversationTurn(speaker: Speaker.system, text: 'Usually within seven to ten business days after the inspection. Thank you for your patience.'),
    ],
  ),
];
